### ISSUE TITLE
device-virtual micro service fails to start properly

### ISSUE THREAD

**Issue by soumyakantiroychowdhury** [edgexfoundry/docker-device-virtual#2]
I have been able to run all the other containers including `edgex-core-consul`, `edgex-core-metadata` and `edgex-core-data`. I added the IP addresses of the containers in `/etc/hosts` so that those are reachable.

However, when I try to start device-virtual micro service, I get the following error:
`
 [2m2017-05-31 06:16:51.184 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36mo.e.device.virtual.Application           [0;39m  [2m: [0;39m The f
ollowing profiles are active: docker
 [2m2017-05-31 06:17:00.311 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36mo.hibernate.jpa.internal.util.LogHelper  [0;39m  [2m: [0;39m HHH00
0204: Processing PersistenceUnitInfo [
	name: default
	...]
 [2m2017-05-31 06:17:00.715 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36morg.hibernate.Version                    [0;39m  [2m: [0;39m HHH00
0412: Hibernate Core {4.3.11.Final}
 [2m2017-05-31 06:17:00.720 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36morg.hibernate.cfg.Environment            [0;39m  [2m: [0;39m HHH00
0206: hibernate.properties not found
 [2m2017-05-31 06:17:00.727 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36morg.hibernate.cfg.Environment            [0;39m  [2m: [0;39m HHH00
0021: Bytecode provider name : javassist
 [2m2017-05-31 06:17:02.550 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36mo.hibernate.annotations.common.Version   [0;39m  [2m: [0;39m HCANN
000001: Hibernate Commons Annotations {4.0.5.Final}
 [2m2017-05-31 06:17:02.681 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36morg.hibernate.dialect.Dialect            [0;39m  [2m: [0;39m HHH00
0400: Using dialect: org.hibernate.dialect.H2Dialect
 [2m2017-05-31 06:17:02.867 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36mo.h.h.i.ast.ASTQueryTranslatorFactory    [0;39m  [2m: [0;39m HHH00
0397: Using ASTQueryTranslatorFactory
 [2m2017-05-31 06:17:04.016 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36morg.hibernate.tool.hbm2ddl.SchemaExport  [0;39m  [2m: [0;39m HHH00
0227: Running hbm2ddl schema export
 [2m2017-05-31 06:17:04.029 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36morg.hibernate.tool.hbm2ddl.SchemaExport  [0;39m  [2m: [0;39m HHH00
0230: Schema export complete
 [2m2017-05-31 06:17:09.957 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36mo.e.device.virtual.BaseService           [0;39m  [2m: [0;39m servi
ce device-virtual has service id 592e5f72e4b09de40f651d42
 [2m2017-05-31 06:17:09.958 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36mo.e.device.virtual.BaseService           [0;39m  [2m: [0;39m Servi
ce registered with id: 592e5f72e4b09de40f651d42
 [2m2017-05-31 06:17:10.441 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36mo.e.device.virtual.data.DeviceStore      [0;39m  [2m: [0;39m Devic
e service has 0 devices.
 [2m2017-05-31 06:17:12.462 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36mo.e.device.virtual.scheduling.Scheduler  [0;39m  [2m: [0;39m loadi
ng schedules
 [2m2017-05-31 06:17:24.389 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36mo.e.device.virtual.scheduling.Scheduler  [0;39m  [2m: [0;39m creat
ed schedule context 592e5f7be4b09de40f651d43 'Interval-15s' initial start time 2017-05-31T06:17:39Z[GMT]
 [2m2017-05-31 06:17:24.391 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36mo.e.d.v.scheduling.ScheduleContext       [0;39m  [2m: [0;39m addin
g schedule event 592e5f7de4b09de40f651d45 'device-virtual-Discovery' to schedule 592e5f7be4b09de40f651d43 'Interval-15s'
 [2m2017-05-31 06:17:24.393 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36mo.e.device.virtual.scheduling.Scheduler  [0;39m  [2m: [0;39m loade
d schedules
 [2m2017-05-31 06:17:24.394 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36mo.e.device.virtual.Initializer           [0;39m  [2m: [0;39m Initi
alized device service successfully
 [2m2017-05-31 06:17:24.395 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36mo.e.device.virtual.BaseService           [0;39m  [2m: [0;39m initi
alization successful.
 [2m2017-05-31 06:17:28.259 [0;39m  [33m WARN [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36mc.n.c.sources.URLConfigurationSource     [0;39m  [2m: [0;39m No UR
Ls will be polled as dynamic configuration sources.
 [2m2017-05-31 06:17:28.260 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36mc.n.c.sources.URLConfigurationSource     [0;39m  [2m: [0;39m To en
able URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
 [2m2017-05-31 06:17:28.276 [0;39m  [33m WARN [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36mc.n.c.sources.URLConfigurationSource     [0;39m  [2m: [0;39m No UR
Ls will be polled as dynamic configuration sources.
 [2m2017-05-31 06:17:28.276 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36mc.n.c.sources.URLConfigurationSource     [0;39m  [2m: [0;39m To en
able URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
 [2m2017-05-31 06:17:29.176 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[ool-11-thread-1] [0;39m  [36mo.edgexfoundry.device.virtual.HeartBeat  [0;39m  [2m: [0;39m This 
is the device-virtual device service.
 [2m2017-05-31 06:17:30.927 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[           main] [0;39m  [36mo.e.device.virtual.Application           [0;39m  [2m: [0;39m Start
ed Application in 50.942 seconds (JVM running for 55.466)
This is the device-virtual micro service
 [2m2017-05-31 06:17:34.907 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[cTaskExecutor-1] [0;39m  [36mo.e.d.v.s.i.ApplicationInitializerImpl   [0;39m  [2m: [0;39m waiti
ng for Core Data Micro Service fully starts up...
 [2m2017-05-31 06:17:37.938 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[cTaskExecutor-1] [0;39m  [36mo.e.d.v.s.i.ApplicationInitializerImpl   [0;39m  [2m: [0;39m waiti
ng for Core Data Micro Service fully starts up...
 [2m2017-05-31 06:17:39.159 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[ool-11-thread-1] [0;39m  [36mo.e.device.virtual.scheduling.Scheduler  [0;39m  [2m: [0;39m execu
ting schedule 592e5f7be4b09de40f651d43 'Interval-15s' at 2017-05-31T06:17:39Z[GMT]
 [2m2017-05-31 06:17:39.393 [0;39m  [31mERROR [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[ool-11-thread-1] [0;39m  [36mo.e.d.v.s.ScheduleEventHTTPExecutor      [0;39m  [2m: [0;39m excep
tion executing event 592e5f7de4b09de40f651d45 'device-virtual-Discovery' url 'HTTP://device-virtual:49990/api/v1/discovery' body '' exception device-virtual
java.net.UnknownHostException: device-virtual
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
	at org.edgexfoundry.device.virtual.scheduling.ScheduleEventHTTPExecutor.execute(ScheduleEventHTTPExecutor.java:64)
	at org.edgexfoundry.device.virtual.scheduling.ScheduleEventExecutor.execute(ScheduleEventExecutor.java:66)
	at org.edgexfoundry.device.virtual.scheduling.ScheduleEventExecutor.execute(ScheduleEventExecutor.java:53)
	at org.edgexfoundry.device.virtual.scheduling.Scheduler.schedule(Scheduler.java:134)
	at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
 [2m2017-05-31 06:17:41.000 [0;39m  [32m INFO [0;39m  [35m6 [0;39m  [2m--- [0;39m  [2m[cTaskExecutor-1] [0;39m  [36mo.e.d.v.s.i.ApplicationInitializerImpl   [0;39m  [2m: [0;39m waiti
ng for Core Data Micro Service fully starts up...
`
I looked into the code and found that `device-virtual` attempts to ping both `edgex-core-metadata` and `edgex-core-data`, in that order. Since it fails to detect Core Data micro service, I checked the connectivity from a shell of the container. 

This is my setting in `/etc/hosts`:

`172.17.0.3   edgex-core-consul
172.17.0.5   edgex-mongo
172.17.0.6   edgex-support-logging
172.17.0.8   edgex-core-metadata
172.17.0.9   edgex-core-data
172.17.0.10  edgex-support-notifications
172.17.0.11  edgex-support-scheduler
172.17.0.12  edgex-export-client
172.17.0.13  edgex-export-distro
172.17.0.14  edgex-support-rulesengine`

I tried with `edgex-coredata` as well, with no result.

Any idea why I face this issue?

Thanks in advance.

**Comment by trcox** [comment]
The service name in the application.properties file was to blame here due to the migration.

Fixed in the affected repositories and the Docker images have been updated.
